# Generated by Django 6.0 on 2026-01-03 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('bank', models.CharField(blank=True, max_length=80)),
                ('card_number', models.CharField(blank=True, max_length=32)),
                ('pin', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('broken', 'Broken'), ('hold', 'Hold')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('hold', 'Hold')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField()),
                ('amount_rub', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.card')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('withdrawn_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission_rub', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='core.card')),
            ],
            options={
                'unique_together': {('date', 'card')},
            },
        ),
    ]
