# Generated by Django 6.0 on 2026-01-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='fully_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
