# Generated by Django 6.0 on 2026-01-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cardgroup_card_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='group',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
