# Generated by Django 6.0 on 2026-01-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bank_color'),
        ('core', '0010_withdrawal_timestamp'),
    ]

    operations = [
    ]
